# Generated by Django 4.2.6 on 2023-11-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=250, null=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_expert", models.BooleanField(default=False)),
                ("password", models.CharField(blank=True, max_length=250)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
