# Generated by Django 4.2.6 on 2024-06-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_user_university"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
