# Generated by Django 4.2.6 on 2024-06-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_classroom_group_module_timeslot_teacher_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='time',
            field=models.CharField(choices=[('8h:00-9h:30', '8h:00-9h:30'), ('9h:30-11h:00', '9h:30-11h:00'), ('11h:00-12h:30', '11h:00-12h:30'), ('12h:30-14h:00', '12h:30-14h:00'), ('14h:00-15h:30', '14h:00-15h:30'), ('15h:30-17h:00', '15h:30-17h:00')], default='', max_length=20),
        ),
    ]
