# Generated by Django 4.2.6 on 2024-06-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_timeslot_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time_slot',
        ),
        migrations.AlterField(
            model_name='group',
            name='school_year',
            field=models.CharField(choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], default='', max_length=20),
        ),
    ]
