# Generated by Django 4.2.6 on 2024-06-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='type',
            field=models.CharField(choices=[('TD', 'TD'), ('TP', 'TP'), ('COURS', 'COURS')], default='', max_length=20),
        ),
    ]
