# Generated by Django 4.2.6 on 2024-06-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_timeslot_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='group',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='group',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='group',
            name='specialty',
        ),
        migrations.AddField(
            model_name='schedule',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='school_year',
            field=models.CharField(choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.group'),
        ),
    ]
