# Generated by Django 4.2.6 on 2024-06-16 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_group_grade_remove_group_school_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='type',
            field=models.CharField(choices=[('TD', 'TD'), ('TP', 'TP'), ('COURS', 'COURS'), ('ONLINE', 'ONLINE')], default='', max_length=20),
        ),
    ]
