# Generated by Django 4.2.6 on 2024-06-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_module_user_schedule_user_teacher_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='cours_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='td_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='tp_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
