# Generated by Django 4.2.6 on 2024-06-18 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_module_cours_hours_alter_module_td_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='planning',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='main.planning'),
        ),
        migrations.AddField(
            model_name='group',
            name='planning',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.planning'),
        ),
        migrations.AddField(
            model_name='module',
            name='planning',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.planning'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='planning',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='main.planning'),
        ),
        migrations.RemoveField(
            model_name='planning',
            name='schedules',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='main.classroom'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='main.module'),
        ),
        migrations.AddField(
            model_name='planning',
            name='schedules',
            field=models.ManyToManyField(blank=True, null=True, related_name='plannings', to='main.schedule'),
        ),
    ]
