# Generated by Django 4.2.6 on 2024-06-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_classroom_planning_group_planning_module_planning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.planning'),
        ),
    ]
