# Generated by Django 4.2.6 on 2024-06-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_classroom_planning_alter_teacher_planning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.planning'),
        ),
    ]
