# Generated by Django 4.2.6 on 2024-06-24 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_group_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='t', to='main.module'),
        ),
    ]
