# Generated by Django 4.2.6 on 2024-06-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_classroom_planning_remove_module_planning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='semester',
        ),
        migrations.AddField(
            model_name='planning',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='school_year',
            field=models.CharField(choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='planning',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
