# Generated by Django 4.2.6 on 2024-06-24 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='schedules',
        ),
        migrations.AddField(
            model_name='schedule',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='main.planning'),
        ),
    ]
