# Generated by Django 4.2.6 on 2024-06-24 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_group_name_remove_planning_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='schedules',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='semester',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='school_year',
            field=models.CharField(choices=[('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='planning',
            name='semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='main.planning'),
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='planning',
        ),
        migrations.RemoveField(
            model_name='module',
            name='planning',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='planning',
        ),
        migrations.AddField(
            model_name='classroom',
            name='planning',
            field=models.ManyToManyField(blank=True, null=True, related_name='classrooms', to='main.planning'),
        ),
        migrations.AddField(
            model_name='module',
            name='planning',
            field=models.ManyToManyField(blank=True, null=True, related_name='modules', to='main.planning'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='planning',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='main.planning'),
        ),
    ]
